### PR TITLE
Add preload request parameter

### PR DESCRIPTION
**Pull request by iainmcgin**
The client's first hint or retrieve request is specified on the
provider frame URI, allowing backends to preload data into the
page for faster serving.

### CODE REVIEW

**Comment by TMSCH** [comment]
Have you considered URL length constraints? It seems that the recommendation is around 2k, however, with such extensible options passed in the URL, I'd assume this added query parameter could quickly grow in size. This could potentially break IDP servers that have such size limitations. What do you think?

**Comment by iainmcgin** [comment]
I don't expect this to be much longer than the URIs that we generate for OAuth2 authorization, and I prefer doing this than pulling out specific pieces of the request. One other possibility would be to use a protocol buffer instead, but so much of the content is string based that I don't think it would actually make it that much smaller.

**Comment by iainmcgin** [comment]
Also, we could just drop the preload parameter if it makes the URL too long.

**Comment by tikurahul** [comment]
LGTM

**Pull request merged**
